<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#S03-T04-Pràctica-amb-programació-numèrica" data-toc-modified-id="S03-T04-Pràctica-amb-programació-numèrica-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>S03 T04 Pràctica amb programació numèrica</a></span></li><li><span><a href="#Descripció" data-toc-modified-id="Descripció-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Descripció</a></span><ul class="toc-item"><li><span><a href="#Nivell-1" data-toc-modified-id="Nivell-1-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Nivell 1</a></span><ul class="toc-item"><li><span><a href="#Exercici-1" data-toc-modified-id="Exercici-1-2.1.1"><span class="toc-item-num">2.1.1&nbsp;&nbsp;</span>Exercici 1</a></span></li><li><span><a href="#Exercici-2" data-toc-modified-id="Exercici-2-2.1.2"><span class="toc-item-num">2.1.2&nbsp;&nbsp;</span>Exercici 2</a></span></li><li><span><a href="#Exercici-3" data-toc-modified-id="Exercici-3-2.1.3"><span class="toc-item-num">2.1.3&nbsp;&nbsp;</span>Exercici 3</a></span></li><li><span><a href="#Exercici-4" data-toc-modified-id="Exercici-4-2.1.4"><span class="toc-item-num">2.1.4&nbsp;&nbsp;</span>Exercici 4</a></span></li><li><span><a href="#Exercici-4-Notas-AQUEST-EXERCICI-NO-ES-PER-VALORAR" data-toc-modified-id="Exercici-4-Notas-AQUEST-EXERCICI-NO-ES-PER-VALORAR-2.1.5"><span class="toc-item-num">2.1.5&nbsp;&nbsp;</span>Exercici 4 Notas <strong>AQUEST EXERCICI NO ES PER VALORAR</strong></a></span></li></ul></li></ul></li></ul></div>

# S03 T04 Pràctica amb programació numèrica

# Descripció
* Familiaritza't amb la Programació Numèrica a través de la llibreria NumPy.

## Nivell 1

### Exercici 1
* Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [1]:
# Opcio 1 Treballar amb arrays numpy
import numpy as np

arr = np.array([1, 2, 3, 4, 5,12,3,4,12,6,8])
#arr = np.array([[1, 2, 3, 4, 5],[2,3,4,2,11]])

def funcioArray (array1D):
    if array1D.ndim != 1:
        print (f"La matriu {array1D} es de mes de una '(1)' dimencio.")
    else:
        media = round(np.median(array1D),3)
        medio = round(np.mean(array1D),3)
        deStan = round(np.std(array1D),3)
        var= round(np.var(array1D),3)
  
        print (f"La media es: {media}")
        print (f"El valor medio es: {medio}")
        print (f"La desviacion Standar: {deStan}")
        print (f"La varianza es: {var}")
    
funcioArray(arr)


La media es: 4.0
El valor medio es: 5.455
La desviacion Standar: 3.577
La varianza es: 12.793


In [2]:
# Opcio 2 . Convertir el arraya a un data frame per poder utilitzar la funcio
# especifica de df.describe()
import numpy as np
import pandas as pd

arr = np.array([1, 2, 3, 4, 5,12,3,4,12,6,8])
#arr = np.array([[1, 2, 3, 4, 5],[2,3,4,2,11]])

def funcioArrayDf (array1Ddf):
    if array1Ddf.ndim != 1:
        print (f"La matriu {array1Ddf} es de mes de una '(1)' dimencio.")
    else:
        array1Ddf_df = pd.DataFrame(array1Ddf)
        return array1Ddf_df.describe()
    
funcioArrayDf(arr)



0
count  11.000000
mean    5.454545
std     3.751363
min     1.000000
25%     3.000000
50%     4.000000
75%     7.000000
max    12.000000

### Exercici 2
* Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [3]:
from numpy import random
import pandas as pd

def funciNxN (n):
    matriunn=random.randint(100, size=(n,n))
    return matriunn

funciNxN(5)

array([[82, 69, 56, 69, 72],
       [31, 43, 90, 56, 20],
       [40,  3, 16, 23, 12],
       [94, 79, 78, 64, 30],
       [22, 47, 69, 30, 15]])

### Exercici 3
* Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

In [4]:
def calcul (array):
    print (array.shape)
    sumFila = np.sum([array], axis=1)
    sumColu = np.sum([array], axis=0)
    print (f"La suma per files es igual a: {sumFila}")
    print (f"La suma per columnes es igual a: {sumColu}")
    
calcul(funciNxN(5))    
    

(5, 5)
La suma per files es igual a: [[200 273 231 273 331]]
La suma per columnes es igual a: [[52 65 95 21 96]
 [ 8 82 10 51 93]
 [80 70 20 92 40]
 [55 42 26 48 82]
 [ 5 14 80 61 20]]


### Exercici 4
* Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [5]:
x=[189,190,208,227,239,252,257,274,293,308,316]
y=[402,404,412,425,429,436,440,447,458,469,469]


def CoefCorrel(x,y):
    medx=np.mean(x)
    medy=np.mean(y)
    desx = np.std(x)
    desy = np.std(y)
    sum = 0
    for i in range(0, len(x)):
        sum += ((x[i] - medx) * (y[i] - medy))
    covarianza = sum/(len(x))
    
    correlacio = covarianza/(desx*desy)
    return correlacio


print ("El resultat de la funció per esbrinar l'índex de la correlació es:", CoefCorrel(x,y))
    
# Comprobacio del resultat fent servir la funcio np.corrcoef de numpy

correXY = np.corrcoef(x,y)[0][1]
print ("La Correlacion de X e Y fent servir numpy es:\n", correXY)
    

El resultat de la funció per esbrinar l'índex de la correlació es: 0.9984246043304558
La Correlacion de X e Y fent servir numpy es:
 0.9984246043304555


### Exercici 4 Notas **AQUEST EXERCICI NO ES PER VALORAR**
* IMPORTANT . HI HA UNA DISCREPANCIA ENTRE ELS RESULTATS DE APLICAR LA FORMULA DIRECTAMENT PER CALCULAR EL VALOR DE LA COVARIANÇA (numpy.cov) I ELS RESULTATS DE LA APLICACIO DE LA FORMULA. 

In [6]:
# https://www.superprof.es/apuntes/escolar/matematicas/estadistica/disbidimension/ejercicios-de-correlacion-y-regresion.html

x2=[189,190,208,227,239,252,257,274,293,308,316]
y2=[402,404,412,425,429,436,440,447,458,469,469]
medx=np.mean(x2)
medy=np.mean(y2)
print ("media x:", medx, "\nmedia y", medy)
varx=np.var(x2)
vary=np.var(y2)
print ("Varianza x:", varx, "\nVarianza y", vary)
desx = np.std(x2)
desy = np.std(y2)
print ("Desviacio Estandar x:", desx, "\nDesviacio Estandar y:", desy)

covarXY = np.cov(x2,y2)[0][1]
print ("La Covarianza de X e Y es:\n", covarXY)

# formula per calcul de la covariança per calcular la correlacio lineal
sum = 0
for i in range(0, len(x2)):
    sum += ((x2[i] - medx) * (y2[i] - medy))
covarianza = sum/(len(x2))
print(covarianza)

# correlacion = covarianza/(sqrt(varx*vary))
# print (correlacion1)

correlacion1 = covarianza/(desx*desy)
print (correlacion1)

# sum1 = 0
# for i in range(0, len(x2)):
#     sum1 += (x2[i] * y2[i])
# cova1 = sum1/(len(x2))
# covarianza1 = cova1 - (medx*medy)
# print(covarianza1)


media x: 250.27272727272728 
media y 435.54545454545456
Varianza x: 1812.0165289256197 
Varianza y 520.2479338842975
Desviacio Estandar x: 42.567787456310434 
Desviacio Estandar y: 22.808944164171596
La Covarianza de X e Y es:
 1066.3363636363636
969.396694214876
0.9984246043304558
